#!/bin/sh
# jon 2021
# .config/bspwm/bspwmrc

bspc monitor -d "system" "home" "msg" "web"

bspc config border_width         16
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true


