#!/bin/sh

# [U2L] .config/bspwm/bspwmrc

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d "/" "/home" "/var" "/web" "/" "/" "/" "/" "/" "/root"

bspc config border_width         1
bspc config window_gap           16

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

